//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neoxam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidateresponse
    {
        public int id { get; set; }
        public int idCandidat { get; set; }
        public int idQuestion { get; set; }
        public int idResponse { get; set; }
        public int idTest { get; set; }
    }
}
