//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neoxam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id { get; set; }
        public string company { get; set; }
        public string email { get; set; }
        public string message { get; set; }
        public string name { get; set; }
        public int phone { get; set; }
        public Nullable<System.DateTime> dateMessage { get; set; }
        public bool stateOfMessage { get; set; }
    }
}
