//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neoxam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cv
    {
        public cv()
        {
            this.experienceprofessionelle = new HashSet<experienceprofessionelle>();
            this.skills = new HashSet<skills>();
            this.formation = new HashSet<formation>();
            this.hobbie = new HashSet<hobbie>();
            this.language = new HashSet<language>();
        }
    
        public string path { get; set; }
        public int candidate_id { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual ICollection<experienceprofessionelle> experienceprofessionelle { get; set; }
        public virtual ICollection<skills> skills { get; set; }
        public virtual ICollection<formation> formation { get; set; }
        public virtual ICollection<hobbie> hobbie { get; set; }
        public virtual ICollection<language> language { get; set; }
    }
}
