//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neoxam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.holiday = new HashSet<holiday>();
            this.message = new HashSet<message>();
            this.message1 = new HashSet<message>();
        }
    
        public int id { get; set; }
        public string State { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public int zipCode { get; set; }
        public Nullable<System.DateTime> dateNaissance { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string password { get; set; }
        public bool permis { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public string status { get; set; }
        public int bonusPts { get; set; }
        public int cin { get; set; }
        public int nbChildren { get; set; }
        public string positionHeld { get; set; }
        public Nullable<System.DateTime> recruitmentDate { get; set; }
        public int salary { get; set; }
    
        public virtual ICollection<holiday> holiday { get; set; }
        public virtual ICollection<message> message { get; set; }
        public virtual ICollection<message> message1 { get; set; }
    }
}
