//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neoxam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public string body { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string @object { get; set; }
        public Nullable<int> reciever_id { get; set; }
        public Nullable<int> sender_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
