//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neoxam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class neoxamdbEntities : DbContext
    {
        public neoxamdbEntities()
            : base("name=neoxamdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<answer> answer { get; set; }
        public virtual DbSet<candidate> candidate { get; set; }
        public virtual DbSet<candidateresponse> candidateresponse { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<cv> cv { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<experienceprofessionelle> experienceprofessionelle { get; set; }
        public virtual DbSet<formation> formation { get; set; }
        public virtual DbSet<hobbie> hobbie { get; set; }
        public virtual DbSet<holiday> holiday { get; set; }
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<skills> skills { get; set; }
        public virtual DbSet<test> test { get; set; }
    }
}
