//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neoxam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public question()
        {
            this.answer = new HashSet<answer>();
        }
    
        public int id { get; set; }
        public string questionBody { get; set; }
        public Nullable<int> FK_TEST_QUESTION { get; set; }
    
        public virtual ICollection<answer> answer { get; set; }
        public virtual test test { get; set; }
    }
}
